title:        Jeffrey Veen
feed:         /rss-source.xml
description:   "The personal web site of Jeffrey Veen."
permalink:    jeff/archives/:title.html
layouts_dir:  jeff/_layouts
sass:
    style: compressed