

permalink:      jeff/archives/:title.html
title:          Jeffrey Veen
feed:           /rss-source.xml
description:    "The personal web site of Jeffrey Veen."

#url:           http://127.0.0.1:4000
#url:           http://veen.com/jeff
#url:           http://pixel:81
url:            https://veen.github.io

sass:
    style: compressed

