exclude:        [greg, amy, start, smallbatch, archives, artsci, images]

permalink:      jeff/archives/:title.html
title:          Jeffrey Veen
feed:           /rss-source.xml
description:    "The personal web site of Jeffrey Veen."

url:           http://veen.com
#url:           http://127.0.0.1:4000
#url:           http://pixel:81

sass:
    style: compressed

