<p>This new way of approaching images has been further confirmed and, in fact, made more obvious by the arrival of the hypermedia image-map.  An image-map, of course, is more than just a "map": image-maps aren't just digital versions of the visual representations of physical, geographic space we normally call maps.  "Image-map" is a technical term used in hypermedia development communities to refer to the background programming or coding maneuver of dividing Web page images into invisibly mapped regions that are each hyperlinked to distinct destinations: other Web pages, multimedia files, etc.  Figure 3.1 below demonstrates the basic technical characteristics of an image-map: each of this image's quadrants are linked (independently of the others) to specific referents.</p>

<div align="center">
<table border="0" cellpadding="0" cellspacing="0" width="160">
<tr><td><a href=""><img src="images/basic_map2.gif" width="160" height="140" border="0" alt="" usemap="#basic"></a></td></tr>
<tr><td><img src="images/spacer.gif" width="1" height="3" border="0" alt=""><br><font size="1" face="Verdana,Arial,Helvetica" color="#666666">Figure 3.1<br>Basic image-map</font></td></tr>
</table>
</div>

<map name="basic">
<area name="yellow" alt="yellow" href="yellow.php?returnID=<%=sectionID%>" coords="1,1,79,69">
<area name="red" alt="red" href="red.php?returnID=<%=sectionID%>" coords="81,1,159,69">
<area name="blue" alt="blue" href="blue.php?returnID=<%=sectionID%>" coords="1,71,79,139">
<area name="green" alt="green" href="green.php?returnID=<%=sectionID%>" coords="81,71,159,139">
</map>

<p>When regions of an image are clickable in this way--that is, when clicking on a specific image element serves up some specific data--that image has forever lost any semblance of being objective, non-coded, neutral or perspective-free.  Its structured status is literalized.  Its constituent parts clearly mean something, because, when prompted, they offer a statement--the other Web page or the audio file, for example, that the clickable region links to.</p></p>

<p>The Web's image-mapping capabilities, moreover, tend to change the way users of the Web view <i>all</i> screen images: on the Web, any image could potentially be an image-map, so all screen images tend to be viewed not merely naturalistically--as objective windows to the real--but as composed of significant elements that might be clickable and that are therefore meaningful.  Because so many images on the Web <i>are</i> linked, when one encounters an image that is <i>not</i>, the very lack of a link may cause one to re-examine that image.  In other words, encountering a non-linked element in an environment whose texts so often point away from themselves prompts renewed attention to that non-linked element, to the meaning it, itself, produces.  In such ways, the possibility of the link, as I will argue in more depth in a moment, is now acting as a catalyst in the development of new types of hypermedia-specific visual literacy.</p>

<p>Even though a clickable element in an image-map is granted a certain significance by the data to which it is linked (I call this an element's "click-through" meaning), it also has meaning simply as a visual element: it still functions as a visual element within the grammar of the image in which it appears. The meaning of an image-map, then, is a product of the intersection of several different semantic layers: the meaning of the image as image or as visual artifact, which might include notions of how the image is the deposit of social relationships; the significance of visual elements as constituents of the image (the hallmark of the "new" visual literacy); the click-through meaning of elements; and the significance of any overlaid or surrounding text.</p>

<p>The least understood of these semantic layers--if only because it is the most recently deployed component of visual language--is clearly the click-through.  Understanding acts of visual signification in digital contexts requires a more precise understanding of both this technology and its uses, plus the meaning-making conventions emerging from the intersection of the two.</p>