<% 
returnID=Request.Querystring("returnID")
anchorID=Request.Querystring("anchorID")
%>

<p>I stress that the technologies of hyperconsumption <i>can</i> ideologically position users as passive in order to avoid suggesting that they <i>necessarily</i> do so.  A non-reductionistic account of ideology and subjectivity would acknowledge that the workings of hegemonic or dominant cultures can engender the possibility of their own opposition.  Perhaps Mark Napier's <a href="http://www.potatoland.org/shredder/shredder.html">Shredder</a>, when <a href="http://www.potatoland.org/cgi-bin/shred.pl?http://www.beyond.com">applied to</a> a site like <a href="http://www.beyond.com">beyond.com</a>, points to an example of this process.</p>

<p><img src="images/arrow_l.gif" width="10" height="10" border="0" alt="Back to text"><font size="1" face="Verdana,Arial,Helvetica"><a href="main.php?sectionID=<%=returnID%>#<%=anchorID%>">Back to text</a></font></p>