<?php

if (sectionID==101) {

$title="Introduction";
$subtitle="The 'New' Visual Literacy";
$nextpagetitle="Nothing New, Always New";
$nextpageID=102;

} else if (sectionID==102) {

$title="Introduction";
$subtitle="Nothing New, Always New";
$nextpagetitle="The Reception of Digitally Produced Images";
$nextpageID=201;

} else if (sectionID==201) {

$title="The Reception of Digitally Produced Images";
$subtitle="Graphics Production and Editing";
$nextpagetitle="Pixels, Bits, and Meaning";
$nextpageID=202;

} else if (sectionID==202) {

$title="The Reception of Digitally Produced Images";
$subtitle="Pixels, Bits, and Meaning";
$nextpagetitle="Image-maps and the Semantic Layers of Digital Images";
$nextpageID=301;

} else if (sectionID==301) {

$title="Reading Hypermedia";
$subtitle="Image-maps and the Semantic Layers of Digital Images";
$nextpagetitle="Visual Click-Through and the Hypertext Link";
$nextpageID=302;

} else if (sectionID==302) {

$title="Reading Hypermedia";
$subtitle="Visual Click-Through and the Hypertext Link";
$nextpagetitle="The Rhetoric of the Click-Through";
$nextpageID=303;

} else if (sectionID==303) {

$title="Reading Hypermedia";
$subtitle="The Rhetoric of the Click-Through: Possible Ways of Reading";
$nextpagetitle="Beyond Metaphor";
$nextpageID=304;

} else if (sectionID==304) {

$title="Reading Hypermedia";
$subtitle="Beyond Metaphor";
$nextpagetitle="Emerging Technologies, Emerging Conventions";
$nextpageID=305;

} else if (sectionID==305) {

$title="Reading Hypermedia";
$subtitle="Emerging Technologies, Emerging Conventions";
$nextpagetitle="Why one cannot Conclude";
$nextpageID=401;

} else if (sectionID==401) {

$title="Conclusion";
$subtitle="Why one cannot Conclude";
$nextpagetitle="";
$nextpageID=500;

} else if (sectionID==500) {

$title="Works Cited";
$nextpagetitle="";

} else if (sectionID==600) {

$title="Note";
$nextpagetitle="";

}
?>